# Generated by Django 4.1 on 2022-08-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('friends', models.ManyToManyField(to='catalog.person')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('lessonsTaken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lessons')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.person')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='members',
            field=models.ManyToManyField(through='catalog.School', to='catalog.person'),
        ),
    ]
